steps:

# 1. Build the Docker image
- name: gcr.io/cloud-builders/docker
  id: Build
  args:
    [
      "build",
      "-t",
      "europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA",
      "."
    ]

# 2. Push the image to Artifact Registry
- name: gcr.io/cloud-builders/docker
  id: Push
  args:
    [
      "push",
      "europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA"
    ]

# Get Credentials
- name: gcr.io/cloud-builders/gcloud
  id: Get Credentials
  args:
    [
      "container",
      "clusters",
      "get-credentials",
      "nfc-1",
      "--zone",
      "europe-north2b",
      "--project",
      "$PROJECT_ID"
    ]


# 3. Update the image in kustomize
- name: gcr.io/cloud-builders/kubectl
  id: Kustomize Replace Image
  entrypoint: "bash"
  args:
    - "-c"
    - |
      kustomize edit set image static-site=europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA

# 4. Deploy to GKE
- name: gcr.io/cloud-builders/kubectl
  id: Deploy
  args:
    [
      "apply",
      "-k",
      "."
    ]

# 5. Wait for rollout
- name: gcr.io/cloud-builders/kubectl
  id: Wait Rollout
  args:
    [
      "rollout",
      "status",
      "deployment/gke-test",
    ]

substitutions:
  _CLUSTER_NAME: "nfc-1"
  _CLUSTER_LOCATION: "europe-north2b"

# GKE permissions
options:
  logging: CLOUD_LOGGING_ONLY

# Connect to GKE before kubectl is used
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/gke-sa-key/versions/latest
      env: "GKE_SA_KEY"

# GKE auth
serviceAccount: $PROJECT_ID@appspot.gserviceaccount.com

