steps:
  # Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-f'
      - Test1/Dockerfile
      - '-t'
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA'
      - Test1
    id: Build

  # Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA'
    id: Push

  # Get Credentials
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - $_CLUSTER_NAME
      - '--zone'
      - $_CLUSTER_LOCATION
      - '--project'
      - $PROJECT_ID
    id: Get-Credentials

  # Kustomize
  - name: gcr.io/cloud-builders/kustomize
    args:
      - edit
      - set
      - image
      - receiver=europe-north2-docker.pkg.dev/$PROJECT_ID/nfc-images/receiver:$SHORT_SHA
    id: Kustomize-Replace-Image
    dir: Test1/kubernetes

  # Apply
  - name: gcr.io/cloud-builders/kubectl
    args:
      - apply
      - '-k'
      - Test1/kubernetes
    id: Deploy

  # Wait 
  - name: gcr.io/cloud-builders/kubectl
    args:
      - rollout
      - status
      - deployment/receiver
    id: Wait-Rollout
    dir: Test1/kubernetes

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _CLUSTER_NAME: nfc-1
  _CLUSTER_LOCATION: europe-north2-b
