apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-router
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /api/validate-access
        pathType: Prefix
        backend:
          service:
            name: validate-access-service
            port:
              number: 80
